version: 2
updates:
  # Enable npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jhjdev"
    assignees:
      - "jhjdev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    
    # Group updates by type
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "vitest*"
          - "@vue/*"
          - "@nuxt/*"
      
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "vue"
          - "nuxt"
          - "pinia"
          - "mongodb"

  # Enable GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jhjdev"
    assignees:
      - "jhjdev"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
